name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-batch-verifier-env-var
    pr_params:
      pollingInterval: $(pr_pollingInterval)
      pollingActive: ${{ eq(variables['pr_pollingActive'], 'true') }}
    snd2_params:
      pollingInterval: $(snd2_pollingInterval)
      pollingActive: ${{ eq(variables['snd2_pollingActive'], 'true') }}
    dev_params:
      pollingInterval: $(dev_pollingInterval)
      pollingActive: ${{ eq(variables['dev_pollingActive'], 'true') }}
    test_params:
      pollingInterval: $(test_pollingInterval)
      pollingActive: ${{ eq(variables['test_pollingActive'], 'true') }}
    pre_params:
      pollingInterval: $(pre_pollingInterval)
      pollingActive: ${{ eq(variables['pre_pollingActive'], 'true') }}
    prd_params:
      pollingInterval: $(prd_pollingInterval)
      pollingActive: ${{ eq(variables['prd_pollingActive'], 'true') }}
