services:
  ffc-pay-batch-verifier:
    build:
      context: .
      target: production
    image: ffc-pay-batch-verifier
    container_name: ffc-pay-batch-verifier
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-batch-verifier-local
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"

  ffc-pay-batch-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.20.1
    command: "azurite-blob --loose --blobHost 0.0.0.0"
