services:
  ffc-pay-batch-verifier:
    build:
      context: .
      target: production
    image: ffc-pay-batch-verifier
    container_name: ffc-pay-batch-verifier
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-batch-verifier-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
