{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-batch-verifier.container-secret") -}}
{{- define "ffc-pay-batch-verifier.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
    APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
